[build]
  # Build command for Vite React app
  command = "npm run build"
  
  # Output directory where Vite builds to
  publish = "dist"
  
  # Node.js version for build environment
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Ensure proper npm version and build environment
  NPM_FLAGS = "--prefix=/opt/buildhome/.nodejs/node_modules/.bin/"
  NODE_ENV = "production"

# SPA (Single Page Application) routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for production
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"