name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] Brief description of the feature"
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Describe the current limitation or pain point.
      placeholder: |
        I'm always frustrated when...
        Currently it's difficult to...
        Users struggle with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to see...
        The feature should...
        It would work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        I also considered...
        Another approach could be...
        Alternative implementations...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocks core functionality)
        - High (Significantly improves workflow)
        - Medium (Nice to have improvement)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Authentication
        - Character Management
        - AI Generation
        - User Interface
        - API/Backend
        - Database
        - Theme System
        - Project Management
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (Small change, 1-2 days)
        - Medium (Moderate change, 1-2 weeks)
        - High (Major feature, 2-4 weeks)
        - Very High (Large feature, 1+ months)
        - Unknown

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how different users would interact with this feature.
      placeholder: |
        As a [user type], I want to [action] so that [benefit].
        
        Example:
        As a content creator, I want to duplicate characters so that I can create similar characters faster.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups, wireframes, or visual examples.
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations
      description: Any technical requirements, constraints, or implementation notes?
      placeholder: |
        - Performance considerations
        - Security implications
        - Database changes needed
        - API modifications required

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce any breaking changes?
      options:
        - No breaking changes
        - Minor breaking changes (with migration path)
        - Major breaking changes (requires version bump)
        - Unknown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: |
        - Links to similar features in other applications
        - Research or documentation
        - Community feedback
        - Business justification

  - type: checkboxes
    id: research
    attributes:
      label: Research Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the roadmap for similar planned features
          required: true
        - label: I have considered the impact on existing users
          required: true
        - label: I have thought about potential security implications
          required: false
        - label: I have considered accessibility requirements
          required: false