global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@fablecraft.app'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
      
    # Warning alerts - grouped notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m
      
    # Business alerts - stakeholder notifications
    - match:
        category: business
      receiver: 'business-alerts'
      group_wait: 5m
      repeat_interval: 2h
      
    # Security alerts - security team notifications
    - match_re:
        alertname: '.*Security.*|.*Auth.*'
      receiver: 'security-alerts'
      group_wait: 0s
      repeat_interval: 10m

# Alert receivers/notification channels
receivers:
  # Default webhook (for testing)
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@fablecraft.app'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }} - FableCraft'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Service: {{ .CommonLabels.service }}
          
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Runbook: {{ .CommonAnnotations.runbook_url }}
        headers:
          Priority: 'high'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: 'danger'
    webhook_configs:
      - url: '${PAGERDUTY_WEBHOOK_URL}'
        send_resolved: true

  # Warning alerts - email only
  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@fablecraft.app'
        subject: '⚠️ WARNING: {{ .GroupLabels.alertname }} - FableCraft'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Service: {{ .CommonLabels.service }}
          
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-warning'
        title: '⚠️ Warning Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: 'warning'

  # Business alerts - stakeholder notifications
  - name: 'business-alerts'
    email_configs:
      - to: 'business@fablecraft.app'
        subject: '📊 BUSINESS ALERT: {{ .GroupLabels.alertname }} - FableCraft'
        body: |
          Business Alert: {{ .GroupLabels.alertname }}
          Impact: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Please review the business impact and take appropriate action.

  # Security alerts - security team
  - name: 'security-alerts'
    email_configs:
      - to: 'security@fablecraft.app'
        subject: '🔒 SECURITY ALERT: {{ .GroupLabels.alertname }} - FableCraft'
        body: |
          Security Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Immediate investigation required.
        headers:
          Priority: 'high'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: '🔒 Security Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: 'danger'

# Inhibition rules (prevent duplicate alerts)
inhibit_rules:
  # Inhibit warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']

  # Inhibit individual service alerts when service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['service', 'instance']