global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fablecraft-monitor'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Application metrics
  - job_name: 'fablecraft-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    
  # Node.js application metrics
  - job_name: 'fablecraft-server'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/api/metrics'
    scrape_interval: 15s
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    
  # Database metrics (if using Postgres)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    
  # Redis metrics (if using Redis)
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    
  # Nginx metrics (reverse proxy)
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    
  # Application health checks
  - job_name: 'fablecraft-health'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/api/health'
    scrape_interval: 30s
    
  # Performance monitoring
  - job_name: 'fablecraft-performance'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/api/performance/metrics'
    scrape_interval: 60s
    
# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB

# Remote write configuration (for long-term storage)
remote_write:
  - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
    basic_auth:
      username: "${GRAFANA_CLOUD_USERNAME}"
      password: "${GRAFANA_CLOUD_PASSWORD}"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'fablecraft_.*'
        target_label: __tmp_should_remote_write
        replacement: true