spring:
  application:
    name: fablecraft-backend
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    baseline-on-migrate: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            
  cache:
    type: simple # Use Redis in production
    
server:
  port: 8080
  
# AI Service Configuration
ai:
  google:
    api-key: ${GOOGLE_API_KEY_1:}
    fallback-api-key: ${GOOGLE_API_KEY:}
    base-url: https://generativelanguage.googleapis.com
    
  openai:
    api-key: ${OPENAI_API_KEY:}
    base-url: https://api.openai.com
    
# Logging
logging:
  level:
    com.fablecraft: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always