name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths: [ 'FABLECRAFT_MODERN_STACK/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'FABLECRAFT_MODERN_STACK/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'FABLECRAFT_MODERN_STACK/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./FABLECRAFT_MODERN_STACK

      - name: Build project
        run: npm run build
        working-directory: ./FABLECRAFT_MODERN_STACK

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: fablecraft-modern-stack
          directory: ./FABLECRAFT_MODERN_STACK/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}